### ISSUE TITLE
serverless-webpack 3.0.0 is released

### ISSUE THREAD

**Issue by HyperBrain** [ktonon/elm-serverless-demo#4]
I just wanted to inform you, that I finally released serverless-webpack 3.0.0 and you can update your demo officially to 3.0.0.

**Comment by HyperBrain** [comment]
In the meantime we're at `4.0.0` 😄

**Comment by ktonon** [comment]
Thanks for the reminder :) 4350f13122546386085530d8079c8efac829094f
